---
- hosts: localhost
  vars: 
    droplets: 
    - checkbox-one 
    - checkbox-two     
  connection: local
  serial: 1
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:  
    - include: tasks/droplet.yml



- hosts: newdroplets
  become_user: root    
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/checkbox.yml
               

