---
- hosts: localhost
  vars: 
    droplets:
    - prod
    - canary  
  connection: local
  serial: 1
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:  
    - include: tasks/droplet.yml



- hosts: newdroplets
  become_user: root    
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/checkbox.yml
    
    
- hosts: localhost
  vars: 
    droplets:
    - proxy 
  connection: local
  serial: 1
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:  
  - name: Add source key for nodejs
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present
    register: first_run

  - name: Add source repo for nodejs
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_8.x xenial main"
      state: present
      update_cache: yes

  - name: Install packages
    apt:
      name: nodejs
      state: present
  - name: Copy proxy.js
    copy: 
      dest: /usr
      src: /var/lib/jenkins/workspace/checkbox.io/deploy_checkbox/proxy.js
      
  - name: Copy proxy.js
    copy: 
      dest: /usr
      src: /var/lib/jenkins/workspace/checkbox.io/deploy_checkbox/package.json
      
  - name: Run proxy.js
    shell: cd /usr && npm install && node proxy.js
      
    


