---
- hosts: localhost
  vars: 
    droplets:
    - prod
    - canary  
  connection: local
  serial: 1
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:  
    - include: tasks/droplet.yml



- hosts: newdroplets
  become_user: root    
  vars_files:
    - vars.yml
  tasks:
    - include: tasks/checkbox.yml
    
    
- hosts: localhost
  vars: 
    droplets:
    - proxy 
  connection: local
  serial: 1
  gather_facts: no
  vars_files:
    - vars.yml
  tasks:  
    - include: tasks/droplet.yml
               

