#!/bin/sh
GIT_WORK_TREE=/var/lib/jenkins/workspace/newcheckbox/production-www/ git checkout -f
cd /var/lib/jenkins/workspace/newcheckbox/deploy_checkbox && sudo ansible-playbook -i localhost newdroplet.yml




